export const GET_PRODUCT_SUCCES = 'GET_PRODUCT_SUCCES';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';
export const GET_PRODUCT_LOADING = 'GET_PRODUCT_LOADING';

export const ADD_CART_SUCCES = 'ADD_CART__SUCCES';
export const ADD_CART_FAILED = 'ADD_CART__FAILED';
export const ADD_CART_LOADING = 'ADD_CART__LOADING';


export const REMOVE_CART_SUCCES = 'REMOVE_CART_SUCCES';
export const REMOVE_CART_FAILED = 'REMOVE_CART_FAILED';
export const REMOVE_CART_LOADING = 'REMOVE_CART_LOADING';